### ISSUE TITLE
More efficient copyTpl

### ISSUE THREAD

**Issue by codfish** [kentcdodds/generator-kcd-oss#11]
Hey, stumbled upon this repo from watching a video of yours. Thanks for creating all the great content!

https://github.com/kentcdodds/generator-kcd-oss/blob/master/generators/app/index.js#L29

You could name all the files correctly and just do the following:

```js
this.fs.copyTpl(this.templatePath('**'), this.destinationPath(), props, {}, { globOptions: { dot: true } })
mv('_package.json', 'package.json')
```

^ assuming you purposely prefixed the `package.json` file to avoid weirdness? Otherwise name that properly and just remove the `mv` function altogether.

I've built a bunch of generators recently for work, so I spent time scouring docs and source code to figure this out cause I thought it was weird that you couldn't just copy all files, hidden or not, at one time. I didn't want to have to copy hidden files individually.

I can contribute this but I didn't bother to open a PR cause I'm not sure if you wanted this. Maybe there's a reason you have it this way that I'm not seeing as well?

**Comment by kentcdodds** [comment]
Thanks @codfish. If I do ever get back in the code a bit I'll remember this at that time. Currently it's working as-is so I'm going to leave it. I don't touch this code very often 😅  Thanks!
