### ISSUE TITLE
Use GitHub actions instead of Travis CI

### ISSUE THREAD

**Issue by MichaelDeBoey** [kentcdodds/generator-kcd-oss#12]
GitHub made their Actions (CI) public, so I think it would be nice to use it in the repo instead of Travis CI.

https://github.com/features/actions

Main benefits I see directly:
- It's a more integrated way of doing CI, where you can just stay on GitHub to watch what happened instead of needing to go to Travis
- Numbers from the [GitHub Universe 2019 keynote](https://www.youtube.com/watch?v=9EoNqyxtSRM) also see a massive time improvement ([Pinterest had their pipeline down from 80 to 10 mins](https://youtu.be/9EoNqyxtSRM?t=640)) when using GitHub Actions

**Comment by kentcdodds** [comment]
Thanks, but I don't see much reason for moving from my current setup.
