### ISSUE TITLE
No matching version found for @rollup/plugin-commonjs@^19.0.1

### ISSUE THREAD

**Issue by akashshyamdev** [kentcdodds/generator-kcd-oss#54]
Hey,

I just ran `yo kcd-oss` and I get the following error:
![Screenshot 2021-09-01 at 20 31 56](https://user-images.githubusercontent.com/56759828/131695332-38774fa9-dfb8-42ef-851a-f0ab65943701.png)

**Comment by kentcdodds** [comment]
Sorry, this package isn't meant to be used by anyone but myself. Please feel free to fork and adjust for your own use case. I don't have time to maintain it for anyone else.
